### ISSUE TITLE
#next branch won't compile after updating webpack

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#136]
Looks like trouble with the webpack.config and remarkable maybe, I'm not a webpack 2 expert yet though..

```
git clone https:/github.com/rrag/react-stockcharts -b next
npm i
npm run watch


...
> react-stockcharts@0.5.0 modernizr /git/react-stockcharts
> modernizr -c config/modernizr-config.json -d ./build/dist/modernizr.js

> Modernizr build saved to build/dist/modernizr.js

> /git/react-stockcharts/webpack/lib/webpack.js:16
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^
> WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'remarkable'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         / test: /\.xxx$/, / may apply this only for some modules
         options: {
           remarkable: ...
         }
       })
     }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/git/react-stockcharts/webpack/lib/webpack.js:16:9)
    at processOptions (/git/react-stockcharts/webpack-dev-server/bin/webpack-dev-server.js:269:17)
    at Object.<anonymous> (/git/react-stockcharts/webpack-dev-server/bin/webpack-dev-server.js:297:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3


```

**Comment by rrag** [comment]
I guess  2.1.0-beta.25 is out and it has some validations on the config, for now change package.json to

- "webpack": "^2.1.0-beta.22",
- "webpack": "2.1.0-beta.22",

to pin to a version

**Comment by itsjimbo** [comment]
Thanks @rrag , it's back to normal now..

**Comment by rrag** [comment]
Fixed, please try with a fresh clone and npm install
