### ISSUE TITLE
PriceCoordinate

### ISSUE THREAD

**Issue by exdeniz** [rrag/react-stockcharts#339]
PriceCoordinate not work with AreaSeries or LineSeries

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `AreaChart`.
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `AreaChart`.
    at invariant (http://localhost:3000/_next/1505708263211/main.js:50:15)
    at instantiateReactComponent (http://localhost:3000/_next/1505708263211/commons.js:6341:23)
    at instantiateChild (http://localhost:3000/_next/1505708263211/commons.js:12496:28)
    at http://localhost:3000/_next/1505708263211/commons.js:12523:16
    at traverseAllChildrenImpl (http://localhost:3000/_next/1505708263211/commons.js:6631:5)
    at traverseAllChildrenImpl (http://localhost:3000/_next/1505708263211/commons.js:6647:23)
    at traverseAllChildren (http://localhost:3000/_next/1505708263211/commons.js:6726:10)
    at Object.instantiateChildren (http://localhost:3000/_next/1505708263211/commons.js:12522:7)
    at ReactDOMComponent._reconcilerInstantiateChildren (http://localhost:3000/_next/1505708263211/commons.js:12186:41)
    at ReactDOMComponent.mountChildren (http://localhost:3000/_next/1505708263211/commons.js:12225:27)
```

**Comment by rrag** [comment]
it works

https://codesandbox.io/s/zr05zjrl0x

what version are you using?

**Comment by exdeniz** [comment]
Check on AreaSeries for example

**Comment by rrag** [comment]
updated - https://codesandbox.io/s/zr05zjrl0x

**Comment by exdeniz** [comment]
Thanks, I'll go try
