### ISSUE TITLE
compatibility with next.js -- a lot of warnings and errors

### ISSUE THREAD

**Issue by c9s** [rrag/react-stockcharts#809]
really love this chart library, however, when I am trying to integrate this library with next.js, there are many warnings and errors

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/50894/167087074-77845794-3f11-4b5e-ab19-250cd96bdbe3.png">

**Comment by c9s** [comment]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/50894/167087760-d87c43ba-ca17-4cc5-b511-17c4256e481e.png">

**Comment by c9s** [comment]
Text version:

```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Chart, ChartCanvas, CrossHairCursor, GenericChartComponent, GenericComponent, Label, XAxis, YAxis

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at ChartCanvas (webpack-internal:///./node_modules/react-stockcharts/es/lib/ChartCanvas.js:314:3)
    at CandleStickChartWithAnnotation (webpack-internal:///./src/Chart.js:52:22)
    at div
    at main
    at div
    at Home (webpack-internal:///./pages/index.tsx:25:62)
    at MyApp (webpack-internal:///./pages/_app.tsx:37:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:825:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:949:27)
```

**Comment by qiyang14** [comment]
I face the same issue
